services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: nylon_db
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql
    platform: linux/amd64 #needed to have this to work on M1 Macs, which I am using locally
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: nylon_db
      MYSQL_ROOT_PASSWORD: root
    command: 
      --default-authentication-plugin=mysql_native_password 
      --innodb-use-native-aio=0
      --explicit_defaults_for_timestamp=1
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: